### PR TITLE
Beta Release

### PR DESCRIPTION
**Pull request by JamsRepos**

### CODE REVIEW

**Comment by JamsRepos** [comment]
@albinmedoc Could you look into the above data concerns?

**Comment by albinmedoc** [comment]
> @albinmedoc Could you look into the above data concerns?

Very good that this was caught. It could have been a big security hole.
I'll make sure to fix it.

**Comment by albinmedoc** [comment]
> > @albinmedoc Could you look into the above data concerns?
> 
> Very good that this was caught. It could have been a big security hole. I'll make sure to fix it.

@JamsRepos I have now solved the security alerts in #465

**Comment by JamsRepos** [comment]
> > > @albinmedoc Could you look into the above data concerns?
> > 
> > 
> > Very good that this was caught. It could have been a big security hole. I'll make sure to fix it.
> 
> @JamsRepos I have now solved the security alerts in #465

Good stuff! Let's see what the status is now 👀

**Comment by MrDynamo** [comment]
@albinmedoc absolute legend!

LGTM!

**Review by MrDynamo — APPROVED** [review]

**Pull request merged**
