### PR TITLE
fix: 🐛 Solve some issues with markdown preview

### PR DESCRIPTION
**Pull request by albinmedoc**
Below fixes has been implemented

1. Ordered list rendering correctly
2. Unordered list rendering correctly
3. Only remove padding of the first heading-element at top level of markdown preview
4. Change color of code-snippet to follow the theme

### CODE REVIEW

**Comment by JamsRepos** [comment]
Nice changes, i've tested these and they all work ass intended!

One thing to note though in regards to changing the colour of the code block, do you reckon we should be changing the colour of the WYSIWYG to the same as the colour scheme for the site? As the black background seems a bit out of place.

**Comment by albinmedoc** [comment]
Please take a look if that was what you meant.

**Comment by albinmedoc** [comment]
Ohh, I get it. That was not what you meant. Wait a moment.

**Comment by JamsRepos** [comment]
Haha, for double confirmation it's the black here.

image

**Comment by JamsRepos** [comment]
Bingo, you got it. Approved 🥳

**Comment by albinmedoc** [comment]
> Bingo, you got it. Approved 🥳

You are fast at testing. Good job!

**Pull request merged**
