### PR TITLE
fix(frontend): 🐛 users without token no longer cause error on scan

### PR DESCRIPTION
**Pull request by PhantomMantis**
when scanning plex server causes an error occur when guest account is enabled

### CODE REVIEW

**Comment by PhantomMantis** [comment]
i need someone to test to make sure this still works on jellyfin with these changes

**Comment by JamsRepos** [comment]
> i need someone to test to make sure this still works on jellyfin with these changes

Just testing functionality? Or is there a specific feature in mind that needs testing?

**Comment by JamsRepos** [comment]
@PhantomMantis Scanning works as intended on Jellyfin, not sure what else you require me to test. Both normal avatars and ones without an avatar work fine.

**Review by JamsRepos — APPROVED** [review]

**Comment by MrDynamo** [comment]
Fixes #339

**Pull request merged**
