### PR TITLE
Make user creation workflow aware of the Jellyfin/Emby API differences

### PR DESCRIPTION
**Pull request by equals215**
Related to https://github.com/wizarrrr/wizarr/issues/336

### CODE REVIEW

**Comment by JamsRepos** [comment]
Hi @equals215! Is there any particular reason why you deleted this? We're currently picking things up again and I had seen this linked to an issue.

**Comment by equals215** [comment]
Hi! My contribution was not really clean and it didn't address the whole problem. You still have access to the commit that I made starting to solve the problem.
IMHO the best way to solve the problems that are occurring (and will occur) due to Emby forking further away to Jellyfin is to treat like different types of media servers in wizarr backend

**Comment by JamsRepos** [comment]
> Hi! My contribution was not really clean and it didn't address the whole problem. You still have access to the commit that I made starting to solve the problem. IMHO the best way to solve the problems that are occurring (and will occur) due to Emby forking further away to Jellyfin is to treat like different types of media servers in wizarr backend

Yeah I gathered! Thanks for the swift reply, unfortunately that's the issue we face when it comes to Jellyfin and Emby. I think we are going to support Plex and Jellyfin for the main suite but I think Emby will be re-visited soon. Of course, if your solution works for your instasnce, feel free to remain using it that way. If you'd like to tidy it up and make a new media server entry within the project we'd welcome it with open arms.

Our primary focus will just be on fixing issues that are currently open and face the wider public. Again, thank you for the contribution even though it may not have made it's way through the pipeline.

**Comment by JamsRepos** [comment]
Hi @equals215 just to let you know i've spent a little time seperating the two to give them more a component based approach so in the future if Emby/Jellyfin fork away from eachother some more, we can easily adapt.

Thanks again for your suggestion on the matter, once we've reviewed and tested the PR you should see it enter the beta branch soon.

**Pull request closed without merging**
