### PR TITLE
Updated README logo to reflect repo refactor.

### PR DESCRIPTION
**Pull request by JamsRepos**

### CODE REVIEW

**Comment by JamsRepos** [comment]
This will have to be updated when this gets merged into master.

**Comment by realashleybailey** [comment]
It would have to be `https://raw.githubusercontent.com/Wizarrrr/wizarr/master/apps/wizarr-frontend/src/assets/img/wizard.png`

**Comment by JamsRepos** [comment]
> It would have to be `https://raw.githubusercontent.com/Wizarrrr/wizarr/master/apps/wizarr-frontend/src/assets/img/wizard.png`

Too slow for me sir.

**Comment by realashleybailey** [comment]
Thank you 😂

**Pull request merged**
