### PR TITLE
Beta Release

### PR DESCRIPTION
**Pull request by JamsRepos**

### CODE REVIEW

**Comment by JamsRepos** [comment]
@albinmedoc A few people in Discord are asking for edit functionality of the pre-existing pages? What do you reckon?

**Comment by albinmedoc** [comment]
> @albinmedoc A few people in Discord are asking for edit functionality of the pre-existing pages? What do you reckon?

These pages are conditional depending on whether you have Plex/Jellyfin and Discord. 
It would be possible to edit these by putting them in a separate database table and have them prepopulated with the English hardcoded version (how they look today). 

What we lose with this implementation is multilingualism. Onboarding pages can only be in one language at a time.

I think this sounds like a very good idea, which would have worked well on my Wizarr instance. 

Give me a GO and I'll start development

**Comment by JamsRepos** [comment]
> > @albinmedoc A few people in Discord are asking for edit functionality of the pre-existing pages? What do you reckon?
> 
> These pages are conditional depending on whether you have Plex/Jellyfin and Discord. It would be possible to edit these by putting them in a separate database table and have them prepopulated with the English hardcoded version (how they look today).
> 
> What we lose with this implementation is multilingualism. Onboarding pages can only be in one language at a time.
> 
> I think this still sounds like a very good idea.
> 
> Give me a GO and I'll start development

Feel free! Free reign, I think the language for the instance will be the same for the whole server regardless. So the content would be written in the language of the admin no doubt.

What Wizarr is made for is for easy management of your friends and family, the only issue you'd have with multi-language support is if you ran a big share or something of the sorts, which we don't want to openly support. So for the most part, the language across the server will be the same.

I think you're absolutely fine to crack on, I don't see no issues. 😀

**Comment by JamsRepos** [comment]
@albinmedoc did you want me to merge this PR in now to get these bugs out on the beta or did you want me to wait for the onboarding amends?

**Comment by albinmedoc** [comment]
Go ahead and merge this to beta. 

I'm having a little trouble getting all the onboarding pages editable. Not sure how long it will take.

**Review by MrDynamo — APPROVED** [review]

**Pull request merged**
