### PR TITLE
Fix Jellyfin library access for new users

### LINKED ISSUE #101: [BUG] Jellyfin invitations do not restrict access to library
**Describe the bug**
I tried restricting access to specific libraries to the invited user, but upon user creation, the user had access to all libraries. 

I tried two methods: 
1. Changing the default libraries under the Server Settings page, restricting access that way

2. Upon creating the invitation, I clicked on the advanced tab, and restricted access to libraries that way as well

Both methods resulted in the user getting access to each and every library/folder available. 

**Screenshots**
image
image

**Logs**
N/A as there were no logs that would indicate any sort of an issue
No logs populated at all actually, If there is a debug env var I could set please let me know.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by EthanArmbrust**
Fixes #101

### CODE REVIEW

**Review by realashleybailey — APPROVED** [review]
I have approved this as it looks okay and works, is it possible if you could explain your process as to why you believe this change fixes the bug so we can have a record for it when we come around to rewriting this code for Wizarr V3

**Comment by EthanArmbrust** [comment]
I put a little comment explaining it in the review. I've tested it my personal jellyfin server to confirm that it works.

**Comment by realashleybailey** [comment]
Could you link it for me, I can't seem to find it on my end.

**Comment by EthanArmbrust** [comment]
My review shows as pending so I'll put it here too.

**Comment by realashleybailey** [comment]
Awesome great work, that totally makes sense I appreciate your time in fixing this bug ☺️

**Pull request merged**
